FROM python:3.9.15
COPY requirements.txt /requirements.txt
RUN pip install --user -r /requirements.txt
RUN mkdir /app && mkdir -p /app/json && mkdir -p /app/templates && mkdir -p /app/util
COPY flaskserver.py /app
COPY json/ /app/json
COPY templates/ /app/templates
COPY util/ /app/util
WORKDIR /app
ENV PATH=/home/app/.local/bin:$PATH
CMD ["python","flaskserver.py"]